{application,benchfella,
             [{applications,[kernel,stdlib,elixir]},
              {description,"Microbenchmarking tool for Elixir."},
              {modules,['Elixir.Benchfella','Elixir.Benchfella.CLI.Util',
                        'Elixir.Benchfella.Counter','Elixir.Benchfella.Json',
                        'Elixir.Benchfella.Snapshot',
                        'Elixir.Benchfella.Snapshot.Formatter',
                        'Elixir.Mix.Tasks.Bench','Elixir.Mix.Tasks.Bench.Cmp',
                        'Elixir.Mix.Tasks.Bench.Graph']},
              {registered,[]},
              {vsn,"0.3.5"}]}.
